# fly.toml app configuration file generated for virtual-gm on 2023-04-26T00:14:57-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "virtual-gm"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[[services]]
    internal_port = 8080
    protocol = 'tcp'

    [[services.ports]]
        handlers = ['http']
        port = 8080


[[services]]
    internal_port = 6270
    protocol = 'tcp'

    [[services.ports]]
        handlers = ['http']
        port = 6270

    [[services.tcp_checks]]
        grace_period = "30s"
        interval = "15s"
        restart_limit = 2
        timeout = "2s"