Kineticist_DB = {
    "elemental blast (air)": [
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Air) - Electricity",
            "lvl": 1,
            "traits": ["air", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d6 electricity"},
            "heighten": {"interval": 4, "effect": "1d6 electricity"},
        },
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Air) - Slashing",
            "lvl": 1,
            "traits": ["air", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d6 slashing"},
            "heighten": {"interval": 4, "effect": "1d6 slashing"},
        },
    ],
    "elemental blast (earth)": [
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Earth) Piercing",
            "lvl": 1,
            "traits": ["earth", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 piercing"},
            "heighten": {"interval": 4, "effect": "1d8 piercing"},
        },
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Earth) Bludgeoning",
            "lvl": 1,
            "traits": ["earth", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 bludgeoning"},
            "heighten": {"interval": 4, "effect": "1d8 bludgeoning"},
        },
    ],
    "elemental blast (fire)": {
        "complex": True,
        "category": "kineticist",
        "title": "Elemental Blast (Fire)",
        "lvl": 1,
        "traits": ["fire", "impulse", "kineticist", "primal", "attack"],
        "type": {"value": "attack"},
        "effect": {"success": "1d6 fire"},
        "heighten": {"interval": 4, "effect": "1d6 fire"},
    },
    "elemental blast (metal)": [
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Metal) Piercing",
            "lvl": 1,
            "traits": ["metal", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 piercing"},
            "heighten": {"interval": 4, "effect": "1d8 piercing"},
        },
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Metal) Slashing",
            "lvl": 1,
            "traits": ["metal", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 slashing"},
            "heighten": {"interval": 4, "effect": "1d8 slashing"},
        },
    ],
    "elemental blast (water)": [
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Water) Bludgeoning",
            "lvl": 1,
            "traits": ["water", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 bludgeoning"},
            "heighten": {"interval": 4, "effect": "1d8 bludgeoning"},
        },
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Water) Cold",
            "lvl": 1,
            "traits": ["water", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 cold"},
            "heighten": {"interval": 4, "effect": "1d8 cold"},
        },
    ],
    "elemental blast (wood)": [
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Wood) Bludgeoning",
            "lvl": 1,
            "traits": ["wood", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 bludgeoning"},
            "heighten": {"interval": 4, "effect": "1d8 bludgeoning"},
        },
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Wood) Vitality",
            "lvl": 1,
            "traits": ["wood", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 vitality"},
            "heighten": {"interval": 4, "effect": "1d8 vitality"},
        },
    ],
    "aerial boomerang": {
        "complex": True,
        "category": "kineticist",
        "title": "Aerial Boomerang",
        "lvl": 1,
        "traits": ["air", "impulse", "kineticist", "primal"],
        "type": {"value": "save", "save": "reflex", "type": "basic"},
        "effect": {"failure": "2d4 slashing"},
        "heighten": {"interval": 2, "effect": "1d4 slashing"},
    },
    "flying flame": {
        "complex": True,
        "category": "kineticist",
        "title": "Flying Flame",
        "lvl": 1,
        "traits": ["fire", "impulse", "kineticist", "primal"],
        "type": {"value": "save", "save": "reflex", "type": "basic"},
        "effect": {"failure": "1d6 fire"},
        "heighten": {"interval": 2, "effect": "1d6 fire"},
    },
    "hail of splinters": {
        "complex": True,
        "category": "kineticist",
        "title": "Hail of Splinters",
        "lvl": 1,
        "traits": ["overflow", "impulse", "kineticist", "primal", "wood"],
        "type": {"value": "save", "save": "reflex", "type": "complex"},
        "effect": {
            "critical success": "",
            "success": "1d4 piercing, pd 1d4 bleed / dc15 flat",
            "failure": "1d4 piercing, pd 1d4 bleed / dc15 flat",
            "critical failure": "1d4 piercing, pd 1d4 bleed / dc15 flat ",
        },
        "heighten": {"interval": 2, "effect": "1d4 piercing, hpd 1d4 bleed"},
    },
    "magnetic pinions": {
        "complex": True,
        "category": "kineticist",
        "title": "Magnetic Pinions",
        "lvl": 1,
        "traits": ["overflow", "impulse", "kineticist", "primal", "metal"],
        "type": {
            "value": "attack",
        },
        "effect": {"success": "1d4 piercing, 1d4 bludgeoning"},
        "heighten": {"interval": 2, "effect": "1d4 piercing, 1d4 bludgeoning"},
    },
    "scorching column": {
        "complex": True,
        "category": "kineticist",
        "title": "Scorching Column",
        "lvl": 1,
        "traits": ["fire", "impulse", "kineticist", "primal", "overflow"],
        "type": {"value": "save", "save": "reflex", "type": "basic"},
        "effect": {"failure": "1d6 fire"},
        "heighten": {"interval": 3, "effect": "1d6 fire"},
    },
    "shard strike": [
        {
            "complex": True,
            "category": "kineticist",
            "title": "Shard Strike (Shards)",
            "lvl": 1,
            "traits": ["impulse", "kineticist", "primal", "metal"],
            "type": {"value": "save", "save": "reflex", "type": "basic"},
            "effect": {
                "failure": "1d6 slashing",
                "critical failure": "1d6 piercing, pd 1d6 bleed / dc15 flat ",
            },
            "heighten": {"interval": 2, "effect": "1d6 piercing"},
        },
        {
            "complex": True,
            "category": "kineticist",
            "title": "Shard Strike (Spines)",
            "lvl": 1,
            "traits": ["impulse", "kineticist", "primal", "metal"],
            "type": {"value": "save", "save": "reflex", "type": "basic"},
            "effect": {
                "failure": "1d6 slashing",
                "critical failure": "1d6 slashing, clumsy 1 auto duration: 1 flex myturn",
            },
            "heighten": {"interval": 2, "effect": "1d6 slashing"},
        },
    ],
    "tidal hands": {
        "complex": True,
        "category": "kineticist",
        "title": "Tidal Hands",
        "lvl": 1,
        "traits": ["water", "impulse", "kineticist", "primal", "overflow"],
        "type": {"value": "save", "save": "reflex", "type": "basic"},
        "effect": {"failure": "1d8 bludgeoning"},
        "heighten": {"interval": 2, "effect": "1d8 bludgeoning"},
    },
    "tremor": {
        "complex": True,
        "category": "kineticist",
        "title": "Tremor",
        "lvl": 1,
        "traits": ["earth", "impulse", "kineticist", "primal", "overflow"],
        "type": {"value": "save", "save": "fort", "type": "basic"},
        "effect": {"failure": "1d8 bludgeoning", "critical failure": "1d8 bludgeoning, prone"},
        "heighten": {"interval": 2, "effect": "1d10 bludgeoning"},
    },
    "winter's clutch": {
        "complex": True,
        "category": "kineticist",
        "title": "Winter's Clutch",
        "lvl": 1,
        "traits": ["cold", "impulse", "kineticist", "primal", "water"],
        "type": {"value": "save", "save": "reflex", "type": "basic"},
        "effect": {"failure": "2d4 cold"},
        "heighten": {"interval": 2, "effect": "1d4 cold"},
    },
    # Level 4
    "blazing wave": {
        "complex": True,
        "category": "kineticist",
        "title": "Blazing Wave",
        "lvl": 4,
        "traits": ["fire", "impulse", "kineticist", "primal", "overflow"],
        "type": {"value": "save", "save": "reflex", "type": "basic"},
        "effect": {"failure": "4d6 fire", "critical failure": "4d6 fire, prone"},
        "heighten": {"interval": 2, "effect": "1d6 fire"},
    },
    "lava leap": {
        "complex": True,
        "category": "kineticist",
        "title": "Lava Leap",
        "lvl": 4,
        "traits": ["fire", "impulse", "kineticist", "primal", "overflow"],
        "type": {"value": "save", "save": "reflex", "type": "basic"},
        "effect": {
            "failure": "1d6 bludgeoning, 2d6 fire, Shielded 2 duration: 1 unit: round auto flex self data 'ac +2 c'",
        },
        "heighten": {"interval": 3, "effect": "1d6 bludgeoning, 1d6 fire"},
    },
    "lightning dash": {
        "complex": True,
        "category": "kineticist",
        "title": "Lightning Dash",
        "lvl": 4,
        "traits": ["air", "electricity", "impulse", "kineticist", "primal", "overflow", "move", "polymorph"],
        "type": {"value": "save", "save": "reflex", "type": "basic"},
        "effect": {
            "failure": "2d12 electricity",
        },
        "heighten": {"interval": 3, "effect": "1d12 electricity"},
    },
    "rain of rust": {
        "complex": True,
        "category": "kineticist",
        "title": "Rain of Rust",
        "lvl": 4,
        "traits": ["metal", "water", "impulse", "kineticist", "primal", "composite"],
        "type": {"value": "save", "save": "fort", "type": "complex"},
        "effect": {
            "failure": "3d6 water, pd 1d6 water / dc15 flat, clumsy 1",
        },
        "heighten": {"interval": 2, "effect": "1d6 water"},
    },
    "whirling grindstone": {
        "complex": True,
        "category": "kineticist",
        "title": "Whirling Grindstone",
        "lvl": 4,
        "traits": ["attack", "composite", "earth", "metal", "impulse", "kineticist", "primal"],
        "type": {"value": "attack"},
        "effect": {
            "success": "2d6 slashing, 1d6 fire",
        },
        "heighten": {"interval": 5, "effect": "1d6 slashing, 1d6 fire"},
    },
    # Level 6
}
