Kineticist_DB = {
    "Elemental Blast (Air)": [
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Air) - Electricity",
            "lvl": 1,
            "traits": ["air", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d6 electricity"},
            "heighten": {"interval": 4, "effect": "1d6 electricity"},
        },
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Air) - Slashing",
            "lvl": 1,
            "traits": ["air", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d6 slashing"},
            "heighten": {"interval": 4, "effect": "1d6 slashing"},
        },
    ],
    "Elemental Blast (Earth)": [
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Earth) Piercing",
            "lvl": 1,
            "traits": ["earth", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 piercing"},
            "heighten": {"interval": 4, "effect": "1d8 piercing"},
        },
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Earth) Bludgeoning",
            "lvl": 1,
            "traits": ["earth", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 bludgeoning"},
            "heighten": {"interval": 4, "effect": "1d8 bludgeoning"},
        },
    ],
    "Elemental Blast (Fire)": {
        "complex": True,
        "category": "kineticist",
        "title": "Elemental Blast (Fire)",
        "lvl": 1,
        "traits": ["fire", "impulse", "kineticist", "primal", "attack"],
        "type": {"value": "attack"},
        "effect": {"success": "1d6 fire"},
        "heighten": {"interval": 4, "effect": "1d6 fire"},
    },
    "Elemental Blast (Metal)": [
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Metal) Piercing",
            "lvl": 1,
            "traits": ["metal", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 piercing"},
            "heighten": {"interval": 4, "effect": "1d8 piercing"},
        },
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Metal) Slashing",
            "lvl": 1,
            "traits": ["metal", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 slashing"},
            "heighten": {"interval": 4, "effect": "1d8 slashing"},
        },
    ],
    "Elemental Blast (Water)": [
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Water) Bludgeoning",
            "lvl": 1,
            "traits": ["water", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 bludgeoning"},
            "heighten": {"interval": 4, "effect": "1d8 bludgeoning"},
        },
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Water) Cold",
            "lvl": 1,
            "traits": ["water", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 cold"},
            "heighten": {"interval": 4, "effect": "1d8 cold"},
        },
    ],
    "Elemental Blast (Wood)": [
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Wood) Bludgeoning",
            "lvl": 1,
            "traits": ["wood", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 bludgeoning"},
            "heighten": {"interval": 4, "effect": "1d8 bludgeoning"},
        },
        {
            "complex": True,
            "category": "kineticist",
            "title": "Elemental Blast (Wood) Bludgeoning",
            "lvl": 1,
            "traits": ["wood", "impulse", "kineticist", "primal", "attack"],
            "type": {"value": "attack"},
            "effect": {"success": "1d8 vitality"},
            "heighten": {"interval": 4, "effect": "1d8 vitality"},
        },
    ],
    "aerial boomerang": {
        "complex": True,
        "category": "kineticist",
        "title": "aerial boomerang",
        "lvl": 1,
        "traits": ["air", "impulse", "kineticist", "primal"],
        "type": {"value": "save", "save": "reflex", "type": "basic"},
        "effect": {"failure": "2d4 slashing"},
        "heighten": {"interval": 2, "effect": "1d4 slashing"},
    },
    "flying flame": {
        "complex": True,
        "category": "kineticist",
        "title": "flying flame",
        "lvl": 1,
        "traits": ["fire", "impulse", "kineticist", "primal"],
        "type": {"value": "save", "save": "reflex", "type": "basic"},
        "effect": {"failure": "1d6 fire"},
        "heighten": {"interval": 2, "effect": "1d6 fire"},
    },
    "hail of splinters": {
        "complex": True,
        "category": "kineticist",
        "title": "hail of splinters",
        "lvl": 1,
        "traits": ["overflow", "impulse", "kineticist", "primal", "wood"],
        "type": {"value": "save", "save": "reflex", "type": "complex"},
        "effect": {
            "critical success": "",
            "success": "1d4 piercing, pd 1d4 piercing / dc15 flat",
            "failure": "1d4 piercing, pd 1d4 piercing / dc15 flat",
            "critical failure": "1d4 piercing, pd 1d4 piercing / dc15 flat ",
        },
        "heighten": {"interval": 2, "effect": "1d4 piercing, hpd 1d4 piercing"},
    },
    "magnetic pinions": {
        "complex": True,
        "category": "kineticist",
        "title": "magnetic pinions",
        "lvl": 1,
        "traits": ["overflow", "impulse", "kineticist", "primal", "metal"],
        "type": {
            "value": "attack",
        },
        "effect": {"success": "1d4 piercing, 1d4 bludgeoning"},
        "heighten": {"interval": 2, "effect": "1d4 piercing, 1d4 bludgeoning"},
    },
    # TODO Utility Skill format
}
